from datetime import datetime
from typing import List

from pydantic import BaseModel, Field, HttpUrl


class ResearchRequest(BaseModel):
    """Input received from the API."""

    question: str = Field(
        ...,
        description="Research question provided by the user."
    )


class SubQuestion(BaseModel):
    """One research task generated by the Planner Agent."""

    id: int = Field(
        ...,
        description="Unique identifier for the sub-question."
    )

    question: str = Field(
        ...,
        description="Specific research task."
    )


class ResearchPlan(BaseModel):
    """Planner Agent output."""

    original_question: str

    sub_questions: List[SubQuestion]


class Citation(BaseModel):
    """Evidence supporting one finding."""

    source_url: HttpUrl

    title: str

    retrieved_at: datetime


class ResearchFinding(BaseModel):
    """Research Agent output."""

    sub_question_id: int

    answer: str

    citations: List[Citation]


class ResearchReport(BaseModel):
    """Writer Agent output."""

    original_question: str

    summary: str

    findings: List[ResearchFinding]